apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cp4ba-ecm-cpe-monitor 
  namespace: paramNamespace 
  labels:
    component: ecm
    group: cp4basetup
spec:
  endpoints:
  - interval: 30s
    port: metrics 
    scheme: http
  selector:
    matchLabels:
      servicename: icp4adeploy-cpe-svc
